### ISSUE TITLE
when i trying examples mmt-task-en-fr-nmt.conf

### ISSUE THREAD

**Issue by xiang-xiang-zhu** [lium-lst/nmtpytorch#30]
Traceback (most recent call last):
  File "/home/hx/anaconda3/envs/torch1.8/bin/nmtpy", line 164, in <module>
    loop()
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/nmtpytorch/mainloop.py", line 313, in __call__
    while self.train_epoch():
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/nmtpytorch/mainloop.py", line 238, in train_epoch
    self.do_validation()
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/nmtpytorch/mainloop.py", line 268, in do_validation
    hyps = beam_search([self.net], self.beam_iterator,
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/nmtpytorch/search.py", line 130, in beam_search
    *[f_next(cd, dec.get_emb(idxs, tstep), h_t[tile]) for
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/nmtpytorch/search.py", line 130, in <listcomp>
    *[f_next(cd, dec.get_emb(idxs, tstep), h_t[tile]) for
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/nmtpytorch/layers/decoders/conditional.py", line 200, in f_next
    txt_alpha_t, txt_z_t = self.att(
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/hx/anaconda3/envs/torch1.8/lib/python3.8/site-packages/nmtpytorch/layers/attention/mlp.py", line 52, in forward
    inner_sum = self.ctx2ctx(ctx) + self.hid2ctx(hid)
RuntimeError: The size of tensor a (31) must match the size of tensor b (32) at non-singleton dimension 1

I don't know how to solve it,it seems that the tensor size not euqal?but i don't know which tensors

**Comment by xiang-xiang-zhu** [comment]
hello

**Comment by loicbarrault** [comment]
Hi there, 
this is strange. Is your batch size 32? 
The 2 tensors (ctx and hid) don't have the same shape which should never happen. You should check them.
